config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'signout' => 'sessions#destroy', as: :signout

  resources :places, only: %i(index) do
    collection do
      get 'checked'
      get 'not'
      get 'ok'
    end
  end

  resources :places, path: '', only: %i(show) do
    resource :check, only: %i(update)
  end

  root 'welcome#index'

  namespace :api do
    get 'places/ok'
  end
end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :user
  belongs_to :place

  validates_presence_of :user
  validates_presence_of :place
  validates_presence_of :value
  validates_inclusion_of :value, in: %w(ok not)
  validates_uniqueness_of :place_id, scope: :user_id

  %w(ok not).each do |value|
    scope value, -> { where value: value }
  end

  def self.search(user, place)
    where(user: user, place: place).first_or_initialize
  end
end

app/models/counter.rb
class Counter < ActiveRecord::Base
  validates_presence_of \
    :users,
    :checks,
    :places,
    :checked_places,
    :ok_places,
    :not_places,
    :progress,
    :ok_checks,
    :not_checks

  scope :recent, -> { order(id: :desc) }

  def initialize(*)
    super
    compute_counts
    compute_progress
    compute_checks
  end

  private

  def compute_counts
    self.users = User.count
    self.checks = Check.count
    self.places = Place.count
    self.checked_places = Place.checked.count
    self.ok_places = Place.ok.count
    self.not_places = Place.not.count
  end

  def compute_progress
    self.progress = if can_compute_progress?
      checked_places.to_f / places
    end
  end

  def can_compute_progress?
    places > 0
  end

  def compute_checks
    self.ok_checks = Check.ok.count
    self.not_checks = Check.not.count
  end
end

app/models/place.rb
require "securerandom"
require "uri"

class Place < ActiveRecord::Base
  has_many :checks

  validates_presence_of :url
  validates_uniqueness_of :url, :code

  before_validation :set_code

  def self.default_scope
    where(telegram: true)
  end

  def self.checked
    joins(:checks).distinct
  end

  def self.random_code
    codes.sample
  end

  def self.codes
    @codes ||= pluck(:code)
  end

  %i(ok not).each do |name|
    define_singleton_method name do
      joins(:checks).merge(Check.send(name)).distinct
    end
  end

  alias_attribute :to_param, :code

  def title
    File.basename(path, File.extname(path))
  end

  def path
    URI.parse(url).path
  end

  def checked?
    checks.any?
  end

  def pdf_url
    url.sub(/\.htm$/, ".pdf") if telegram?
  end

  private

  def set_code
    self.code ||= SecureRandom.hex
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :checks

  validates_presence_of :provider, :uid, :name
  validates_uniqueness_of :provider, scope: :uid
  validate :has_nickname_or_email

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.nickname = auth.info.nickname
      user.save!
    end
  end

  def display_name
    name
  end

  def to_auth
    auth = OmniAuth::AuthHash.new attributes.slice("provider", "uid")
    auth.info = attributes.slice("name", "nickname", "email")
    auth
  end

  private

  def has_nickname_or_email
    unless nickname.present? || email.present?
      errors.add :base, :must_have_nickname_or_email
    end
  end
end

app/controllers/api/places_controller.rb
class Api::PlacesController < ApplicationController
  skip_before_action :authorize

  def ok
    render plain: pdf_urls.join("\n")
  end

  private

  def pdf_urls
    Place.ok.limit(1000).map(&:pdf_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :force_http
  before_action :authorize

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue
    nil
  end
  helper_method :current_user

  def counter
    @counter ||= Counter.recent.first_or_initialize
  end
  helper_method :counter

  def authorize
    unless current_user
      redirect_to root_url, alert: "Not Authorized"
    end
  end

  def force_http
    if request.ssl?
      redirect_to protocol: 'http://', status: 301
    end
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  def update
    @place = Place.find_by! code: params[:place_id]
    @check = Check.search current_user, @place
    @check.value = params[:value]
    @check.save!
    redirect_to root_url
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def show
    @place = Place.find_by! code: params[:id]
  end

  def index
    @places = Place.page params[:page]
  end

  def checked
    @places = Place.checked.page params[:page]
    render "index"
  end

  def ok
    @places = Place.send(action_name).page params[:page]
    render "index"
  end
  alias_method :not, :ok
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, only: %i(create failure)

  def create
    user = User.from_omniauth auth
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in"
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Signed out"
  end

  def failure
    redirect_to root_url, alert: "Authentication Error"
  end

  private

  def auth
    request.env["omniauth.auth"]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorize, only: %i(index)

  def index
    if current_user && random_code
      redirect_to place_url(id: random_code)
    end
  end

  private

  def random_code
    @random_code ||= Place.random_code
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def progress_as_percentage
    number_to_percentage(counter.progress * 100, precision: 2)
  rescue
    "N/D"
  end

  def data_tag(value)
    content_tag :span, value, class: "data"
  end
end

app/views/application/_nav.html.erb
<!-- Fixed navbar -->
  <% unless current_user %>
    <nav class="navbar clearfix navbar-fixed-top">
  <% else %>
  <nav class="navbar navbar-default">
    <% end %>
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% unless current_user %>
          <a class="navbar-brand" href="/"><%= image_tag 'logo.png', size: "200x50" %></a>
          <% else %>
          <a class="navbar-brand" href="/"><%= image_tag 'logo_log.png', size: "200x50" %></a>
          <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% unless current_user %>
            <li><a href="/auth/facebook">Ingresar con Facebook</a></li>
            <li><a href="/auth/twitter">Ingresar con Twitter</a></li>
            <% else %>
            <li class="usercurnew"><%= data_tag current_user.display_name %> tenés <%= data_tag current_user.checks.count %> chequeos</li>
            <li><%= link_to "Salir", signout_url %></li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/application/_tracking.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70687106-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es-ar">
<head>
  <title>Balotaje 2015 - Argentina</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", media: 'all', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "tracking" unless Rails.env.development? %>
  <%= render "nav" %>
  <%= yield %>
</body>
</html>

app/views/places/index.html.erb
<h3>
  <%= page_entries_info @places %>
</h3>
<ul>
  <% @places.each do |place| %>
    <li>
      <%= link_to place.title, place %>
    </li>
  <% end %>
</ul>
<%= paginate @places %>

app/views/places/not.html.erb
<h1>Places#not</h1>
<p>Find me in app/views/places/not.html.erb</p>

app/views/places/ok.html.erb
<h1>Places#ok</h1>
<p>Find me in app/views/places/ok.html.erb</p>

app/views/places/show.html.erb
<div class="module">
  <div class="check">
    <%= form_tag [@place, :check], method: :patch do %>
      <%= button_tag "✓", name: "value", value: "ok" %>
      <%= button_tag "✗", name: "value", value: "not" %>
    <% end %>
  </div>
  <ul class="counter">
    <li class="progress_as_percentage">Progreso: <%= data_tag progress_as_percentage %></li>
    <li>Chequeados: <%= link_to number_with_delimiter(counter.checked_places), checked_places_url, class: "data" %> de <%= link_to number_with_delimiter(counter.places), places_path, class: "data" %></li>
    <li><%= link_to number_with_delimiter(counter.ok_places), ok_places_url, class: "data" %> buenos y <%= link_to number_with_delimiter(counter.not_places), not_places_url, class: "data" %> malos</li>
  </ul>
</div>
<div class="place_wrapper">
  <iframe src="<%= @place.url %>" frameborder="0" class="place"></iframe>
  <% if @place.checked? %>
    <h3 class="message">Chequeos anteriores</h3>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Balotaje 2015</h1>
<p>
  Convocatoria abierta para controlar la carga de los resultados provisionales
  de la segunda vuelta de las Elecciones Nacionales en Argentina, 22 de
  noviembre de 2015.
</p>
<h2>Instrucciones</h2>
<ol>
  <li>Entrá con <a href="/auth/twitter">Twitter</a> o <a href="/auth/facebook">Facebook</a> y aceptá la confirmación</li>
  <li>La aplicación te presentará un telegrama y datos cargados</li>
  <li>Si los datos coinciden, marcá el botón <code>✓</code></li>
  <li>Si los datos no coinciden, marcá el botón <code>✗</code></li>
  <li>La aplicación te presentará otro telegrama y así...</li>
  <li>Si te equivocaste, podés volver atrás y marcar</li>
  <li>Si marcás varias veces, solo cuenta una</li>
</ol>
<h2>Resultados parciales</h2>
<ul class="counter">
  <li class="progress_as_percentage">Progreso: <%= data_tag progress_as_percentage %></li>
  <li>Chequeados: <%= data_tag number_with_delimiter(counter.checked_places) %> de <%= data_tag number_with_delimiter(counter.places) %></li>
  <li><%= data_tag number_with_delimiter(counter.ok_places) %> buenos y <%= data_tag number_with_delimiter(counter.not_places) %> malos</li>
</ul>
<h2>Aclaración</h2>
<p>
  Esta aplicación persigue una curiosidad estadística, no apoya a ningún partido
  político ni persigue desautorizar el trabajo de la Dirección Nacional
  Electoral. Los datos de la aplicación son públicos y fueron extraídos del
  sitio de <a href="http://www.resultados.gob.ar/inicio.htm">resultados de las
  elecciones</a>. El ingreso se pide con un mínimo de permisos, para limitar el
  acceso a robots y una desviación en las observaciones.
</p>
<h2>Código fuente y datos abiertos</h2>
<p>
  El código completo de esta aplicación está <a
  href="https://github.com/xymbol/checkup">disponible</a> y liberado con una
  licencia de software libre. Si querés acceso a los datos de los chequeos, por
  favor escribime.
</p>
<h2>Contacto</h2>
<p>
  Por cualquier consulta técnica, inquietud o falla, escribime a
  <a href="https://twitter.com/691hxn">@691hxn</a> en Twitter.
</p>